// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dao

var TableNames = struct {
	ArInternalMetadata string
	Todos              string
	Users              string
}{
	ArInternalMetadata: "ar_internal_metadata",
	Todos:              "todos",
	Users:              "users",
}
